name: "CD"

on:
  pull_request_review_comment:
    types: [created, edited]

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ contains(github.event.comment.body , '/test') }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "A comment ${{ github.event.comment.body  }}"
